# Generated by Django 4.0.5 on 2022-06-23 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userweight',
            old_name='delete_at',
            new_name='deleted_at',
        ),
    ]
